# Generated by Django 3.1.3 on 2020-12-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
    ]
