# Generated by Django 3.1.3 on 2020-12-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20201201_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
    ]
