# Generated by Django 3.1.3 on 2020-11-30 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0002_conversationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversationmessages', to='job.application'),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversationmessages', to=settings.AUTH_USER_MODEL),
        ),
    ]
