# Generated by Django 3.1.3 on 2020-11-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20201130_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
